run:
  timeout: 10m
  deadline: 5m
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustruct
    - varnamelen
    - gochecknoinits
    - wrapcheck
    - funlen
    - depguard
    - nolintlint
    # generics disabled
    - wastedassign
    - rowserrcheck
    # deprecated
    - gomoddirectives
    - tenv
linters-settings:
#  typecheck:
#    enabled: false
  errcheck:
    check-blank: false
    exclude-functions:
      - fmt:.*
  nolintlint:
    require-specific: true

issues:
  exclude-files:
    - ".*_test.go"
