# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: podman-tui
upstream_tag_template: v{version}

srpm_build_deps:
  - git-archive-all

packages:
  podman-tui-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/podman-tui.spec

  podman-tui-centos:
    pkg_tool: centpkg
    specfile_path: rpm/podman-tui.spec

merge_pr_in_ci: false

files_to_sync:
  - src:
      - ".packit.yaml"
      - "rpm/podman-tui.spec"
      - "rpm/vendor-*.tar.gz"
    dest: .

actions:
  fix-spec-file:
    - "bash rpm/packit-copr-rpm.sh"
  post-modifications:
    - |
      bash -xc '
      export CURRENT_DIR=$(pwd)
      export BASE_DIR=${PACKIT_UPSTREAM_REPO}/
      if [ -n "${PACKIT_DOWNSTREAM_REPO}" ] ; then
        VERSION=$(grep -E "[[:space:]]+appVersion\s*=" ${BASE_DIR}/cmd/version.go  | cut -d\" -f2 | sed 's/-//')
        tar -C ${BASE_DIR} -czf "vendor-${VERSION}.tar.gz" vendor/
        cp vendor-${VERSION}.tar.gz ${PACKIT_DOWNSTREAM_REPO}
      fi
      '

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    packages: [podman-tui-fedora]
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64

  - job: copr_build
    trigger: pull_request
    enable_net: true
    packages: [podman-tui-fedora]
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
      - epel-10-x86_64
      - epel-10-aarch64

  - job: copr_build
    trigger: pull_request
    enable_net: true
    packages: [podman-tui-centos]
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64

  - job: propose_downstream
    trigger: release
    update_release: false
    packages:
      - podman-tui-fedora
    dist_git_branches: &build_targets
      - fedora-all
      - epel-9
      - epel-10

  - job: koji_build
    trigger: commit
    packages:
      - podman-tui-fedora
    dist_git_branches: *build_targets

  - job: bodhi_update
    trigger: koji_build
    packages:
      - podman-tui-fedora
    dist_git_branches: *build_targets
